# ------------------------------
# Folders
# ------------------------------
train_folder: "data/raw/train"       # Folder containing raw train audio + txt
test_folder: "data/raw/test"         # Folder containing raw test audio + txt

output_train_folder: "data/processed/train"   # Folder to save sub-audios and train/val CSV
output_test_folder: "data/processed/test"     # Folder to save sub-audios and test CSV

train: "data/train.csv"
test: "data/test.csv"
val: "data/val.csv"

# ------------------------------
# Data processing
# ------------------------------
min_duration: 0.1     # Minimum duration (seconds) of sub-audio clips
val_ratio: 0.2        # Fraction of train data to use as validation

# ------------------------------
# Training hyperparameters
# ------------------------------
epochs: 7
batch_size: 1


# ------------------------------
# Model selection
# ------------------------------
model_name: "microsoft/wavlm-base"   

# ------------------------------
# Visualization
# ------------------------------
confusion_matrix_dir: "./confusion_matrices"

# ------------------------------
# TrainingArguments
# ------------------------------
training_args:
  output_dir: "./results"
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  evaluation_strategy: "epoch"
  save_strategy: "epoch"
  num_train_epochs: 5
  logging_dir: "./logs"
  logging_steps: 10
  learning_rate: 0.00002
  load_best_model_at_end: true
  metric_for_best_model: "macro_f1"

  greater_is_better: true
